genesis-file="/etc/besu/genesis.json"
data-path="/var/lib/besu"
network-id=2026

p2p-host="0.0.0.0"
p2p-port=30303
discovery-enabled=false
static-nodes-file="/etc/besu/static-nodes.json"
permissions-nodes-config-file-enabled=true
permissions-nodes-config-file="/etc/besu/permissions_config.toml"

host-allowlist=["localhost","127.0.0.1","validator1","validator2","validator3","validator4","validator5"]
rpc-http-enabled=true
rpc-http-host="0.0.0.0"
rpc-http-port=8545
rpc-http-api=["ETH","NET","WEB3","QBFT"]
rpc-http-cors-origins=[]

rpc-ws-enabled=true
rpc-ws-host="0.0.0.0"
rpc-ws-port=8546
rpc-ws-api=["ETH","NET","WEB3","QBFT"]

graphql-http-enabled=false
metrics-enabled=true
metrics-host="0.0.0.0"
metrics-port=9545

min-gas-price=0
