import type { Metadata } from "next";
import { MarketingFooter, MarketingNav, Reveal } from "@/components/marketing/premium-marketing";

export const metadata: Metadata = { title: "Architecture", description: "ThreadProof trust boundaries, application layers, proving system and consortium-chain authority." };

const layers = [
  ["People + organizations", "Buyers, factories, auditors and governance participants act through attributed organizational identities.", "Human authority"],
  ["Next.js application", "Coordinates permission-scoped workflows, private commercial records and wallet interactions.", "Workflow"],
  ["Supabase + encrypted state", "Stores RLS-scoped operational data, encrypted witness material and rebuildable chain read models.", "Private data plane"],
  ["Proof + relayer workers", "Generate private witnesses and submit only authorization-bound transactions under fail-closed signing policy.", "Computation"],
  ["Besu + protocol contracts", "Decide canonical order versions, capacity state, nullifiers, credential status, subcontract authorization and Charter execution.", "Canonical authority"],
] as const;

export default function ArchitecturePage() {
  return <main className="premium-page"><MarketingNav />
    <section className="premium-subhero"><div className="premium-subhero-inner"><Reveal><span className="premium-kicker">Architecture</span><h1>Every layer has<br/>one job.</h1><p>ThreadProof is designed so a compromised application component cannot simply promote database state into protocol truth. Coordination, private computation, signing, consensus and governance remain deliberately separate.</p></Reveal></div></section>
    <section className="premium-section"><div className="premium-section-inner"><Reveal><div className="premium-section-heading"><span className="premium-kicker">Trust boundary</span><h2>The application coordinates.<br/>The chain decides.</h2><p>A useful architecture test is simple: if compromising an application component would let an attacker create protocol truth that the contracts would otherwise reject, that component has too much authority.</p></div></Reveal><div className="architecture-stack">{layers.map(([title, body, badge], index) => <Reveal delay={index * 55} key={title}><div className={`arch-layer ${index === layers.length - 1 ? "canonical" : ""}`}><strong>{title}</strong><p>{body}</p><span className="arch-badge">{badge}</span></div></Reveal>)}</div></div></section>
    <section className="premium-section soft"><div className="premium-section-inner"><Reveal><div className="premium-section-heading"><span className="premium-kicker">Two distributed systems</span><h2>Consensus and governance intersect. They do not collapse into each other.</h2><p>QBFT establishes transaction order and finality. The ThreadProof Charter establishes institutional authority for exceptional actions, policy changes and protected disclosure.</p></div></Reveal><div className="tension-grid"><Reveal><article className="tension-pane"><span>Technical consensus</span><h3>What happened first?</h3><div className="tension-list"><div><span>Order transactions</span><i/></div><div><span>Capacity transitions</span><i/></div><div><span>Credential state changes</span><i/></div><div><span>Finalized block order</span><i/></div></div></article></Reveal><Reveal delay={90}><article className="tension-pane private"><span>Institutional governance</span><h3>Who may exercise exceptional authority?</h3><div className="tension-list"><div><span>Policy changes</span><i/></div><div><span>Emergency protocol actions</span><i/></div><div><span>Protected disclosure</span><i/></div><div><span>Privileged role delegation</span><i/></div></div></article></Reveal></div></div></section>
    <section className="premium-section dark"><div className="premium-section-inner"><Reveal><div className="premium-section-heading"><span className="premium-kicker">Fail-closed behavior</span><h2>When canonical state is unavailable, authorization stops.</h2><p>ThreadProof does not fall back to “trust the database for now.” A quorum outage removes liveness, not safety: new authoritative capacity mutations wait until canonical ordering is available again.</p></div></Reveal><Reveal><div className="governance-panel"><div className="governance-summary"><span className="premium-kicker">Chain unavailable</span><h3>Production authorization paused</h3><p>Operators can still inspect local workflow state, but no application row is promoted into canonical capacity authority.</p></div><div className="approval-list"><div className="approval-row"><div><strong>Application workflow</strong><small>Readable where permitted</small></div><span className="approval-state">Available</span></div><div className="approval-row"><div><strong>Proof generation</strong><small>May prepare, but cannot establish final state alone</small></div><span className="approval-state">Non-authoritative</span></div><div className="approval-row"><div><strong>Capacity mutation</strong><small>Requires canonical chain finality</small></div><span className="approval-state approved">Blocked safely</span></div></div></div></Reveal></div></section>
    <MarketingFooter /></main>;
}
