import type { Metadata } from "next";
import { MarketingFooter, MarketingNav, PrivacyLabel, Reveal } from "@/components/marketing/premium-marketing";

export const metadata: Metadata = { title: "Privacy", description: "ThreadProof privacy classes and progressive disclosure model." };

const layers = [
  { tone: "consortium" as const, label: "Consortium-visible", title: "Shared protocol facts", body: "Commitments, credential status, policy references, governance events and other facts needed for consortium coordination." },
  { tone: "shared" as const, label: "Counterparty-confidential", title: "Commercial workflow data", body: "Purchase orders, schedules, allocations and terms remain limited to organizations with a legitimate relationship." },
  { tone: "private" as const, label: "Zero-knowledge private", title: "Cryptographic witness state", body: "Exact certified capacity, remaining capacity, openings and private workloads exist only where proofs require them." },
  { tone: "protected" as const, label: "Governance protected", title: "Due-process information", body: "Protected identities and investigation material remain concealed until the Charter authorizes disclosure." },
] as const;

export default function PrivacyPage() {
  return <main className="premium-page"><MarketingNav />
    <section className="premium-subhero"><div className="premium-subhero-inner"><Reveal><span className="premium-kicker">Privacy model</span><h1>Private by design.<br/>Not private by omission.</h1><p>ThreadProof does not treat “off-chain” as a privacy strategy. Every class of information has an explicit visibility boundary, purpose and authority model.</p></Reveal></div></section>
    <section className="premium-section"><div className="premium-section-inner"><div className="privacy-layers"><Reveal><div className="privacy-orbit"><div className="privacy-ring r1">Consortium-visible</div><div className="privacy-ring r2">Counterparty-confidential</div><div className="privacy-ring r3">Zero-knowledge private</div><div className="privacy-core">Governance<br/>protected</div></div></Reveal><div className="privacy-copy-list">{layers.map((layer, index) => <Reveal delay={index * 60} key={layer.label}><article><PrivacyLabel tone={layer.tone}>{layer.label}</PrivacyLabel><h3>{layer.title}</h3><p>{layer.body}</p></article></Reveal>)}</div></div></div></section>
    <section className="premium-section soft"><div className="premium-section-inner"><Reveal><div className="premium-section-heading"><span className="premium-kicker">Access is visible in the interface</span><h2>The product should never invent a value the user cannot see.</h2><p>ThreadProof uses intentional privacy treatments instead of fake placeholders. The UI explains why information is unavailable and what evidence can still be verified.</p></div></Reveal><div className="credential-grid"><Reveal><article className="credential-object"><PrivacyLabel tone="private">Zero-knowledge private</PrivacyLabel><h3>Remaining capacity</h3><p><strong>Protected by zero-knowledge proof.</strong> Buyers can verify that an order fits without learning the factory's remaining capacity.</p><div className="credential-meta"><div><small>Visible evidence</small><strong>Proof verified</strong></div><div><small>Hidden value</small><strong>Not disclosed</strong></div></div></article></Reveal><Reveal delay={70}><article className="credential-object"><PrivacyLabel tone="shared">Counterparty-confidential</PrivacyLabel><h3>Purchase order terms</h3><p>Only authorized buyer and factory organizations see the detailed commercial record and operational amendments.</p><div className="credential-meta"><div><small>Scope</small><strong>Counterparties</strong></div><div><small>Chain exposure</small><strong>Commitment only</strong></div></div></article></Reveal><Reveal delay={140}><article className="credential-object"><PrivacyLabel tone="protected">Governance protected</PrivacyLabel><h3>Protected supplier identity</h3><p>A reference such as <span className="mono">tp:hidden:7F21</span> remains concealed until a valid due-process proposal reaches its threshold and timelock.</p><div className="credential-meta"><div><small>Initial view</small><strong>Protected reference</strong></div><div><small>Reveal authority</small><strong>Charter execution</strong></div></div></article></Reveal></div></div></section>
    <section className="premium-section dark"><div className="premium-section-inner"><Reveal><div className="premium-section-heading"><span className="premium-kicker">Recovery boundary</span><h2>The chain can verify a commitment without knowing its opening.</h2><p>That is a privacy feature and an availability responsibility. If encrypted witness state is lost, ThreadProof does not use an administrator reset to manufacture a replacement private state.</p></div></Reveal><Reveal><div className="governance-panel"><div className="governance-summary"><PrivacyLabel tone="private">Private witness state</PrivacyLabel><h3>Opening unavailable</h3><p>The active commitment remains canonical, but the next proof cannot be constructed from chain data alone.</p><div className="threshold"><strong>→</strong><span>recertification path</span></div></div><div className="approval-list"><div className="approval-row"><div><strong>1. Close old state</strong><small>Explicitly retire the stranded commitment under the governed recovery procedure.</small></div><span className="approval-state approved">Required</span></div><div className="approval-row"><div><strong>2. Auditor recertifies</strong><small>Create a new attributed physical-world capacity claim.</small></div><span className="approval-state approved">Required</span></div><div className="approval-row"><div><strong>3. Initialize new commitment</strong><small>Resume with a fresh private opening and canonical state.</small></div><span className="approval-state approved">Required</span></div></div></div></Reveal></div></section>
    <MarketingFooter /></main>;
}
