import type { Metadata } from "next";
import { MarketingFooter, MarketingNav, PrivacyLabel, Reveal } from "@/components/marketing/premium-marketing";

export const metadata: Metadata = { title: "Protocol", description: "How ThreadProof verifies private production feasibility and canonical capacity state transitions." };

export default function ProtocolPage() {
  return <main className="premium-page"><MarketingNav />
    <section className="premium-subhero"><div className="premium-subhero-inner"><Reveal><span className="premium-kicker">Protocol</span><h1>Private state.<br/>Publicly verifiable rules.</h1><p>ThreadProof turns certified production capacity into a confidential state machine. Zero-knowledge proves that a transition is valid; the consortium chain decides which private state is current.</p></Reveal></div></section>
    <div className="detail-story-grid">
      <Reveal><section className="detail-story"><div><span className="premium-kicker">01 · Certification</span><h2>Capacity begins as an auditor-attributed claim.</h2><p>An auditor certifies a factory-period-process capacity value. ThreadProof records a cryptographic commitment and credential reference, not the private number itself.</p></div><div className="detail-demo"><PrivacyLabel tone="private">Zero-knowledge private</PrivacyLabel><h3>Certified capacity opening</h3><div className="proof-flow"><div className="proof-step"><span className="index">R₀</span><div><strong>Certified numeric capacity</strong><small>Private witness retained by authorized factory workflow</small></div><span className="masked-value">••••••••</span></div><div className="proof-arrow"/><div className="proof-step verified"><span className="index">C₀</span><div><strong>Capacity commitment</strong><small>Factory × period × process bound</small></div><span className="status-dot">Active</span></div></div></div></section></Reveal>
      <Reveal><section className="detail-story reverse"><div className="detail-demo"><div className="proof-flow"><div className="proof-step"><span className="index">01</span><div><strong>Order workload</strong><small>Quantity × production standard</small></div><span className="masked-value">private</span></div><div className="proof-arrow"/><div className="proof-step"><span className="index">02</span><div><strong>Open current commitment</strong><small>Witness must match the chain's active Cᵢ</small></div><span className="masked-value">••••</span></div><div className="proof-arrow"/><div className="proof-step verified"><span className="index">03</span><div><strong>Prove Rᵢ ≥ workload</strong><small>And derive Rᵢ₊₁ without disclosure</small></div><span className="status-dot">Valid</span></div></div></div><div><span className="premium-kicker">02 · Feasibility</span><h2>A hidden inequality is not enough.</h2><p>The factory cannot choose an arbitrary private “remaining capacity.” The proof must open the exact commitment recognized by the chain, then prove the workload can be consumed from that state.</p></div></section></Reveal>
      <Reveal><section className="detail-story"><div><span className="premium-kicker">03 · Serialization</span><h2>Correct proofs can still compete. Canonical state resolves the race.</h2><p>Two orders can produce valid proofs against the same prior commitment. The first finalized transition consumes that state; later attempts fail because the old commitment is no longer current.</p></div><div className="detail-demo dark"><div className="state-origin"><strong>Current C₄</strong><br/><small>one active state</small></div><div className="state-branches"><article className="state-branch accepted"><small>Order A</small><h3>C₄ → C₅</h3><div className="state-result"><span>Execution</span><b>Accepted</b></div></article><article className="state-branch rejected"><small>Order B</small><h3>C₄ → C₅′</h3><div className="state-result"><span>Execution</span><b>Old state consumed</b></div></article></div></div></section></Reveal>
      <Reveal><section className="detail-story reverse"><div className="detail-demo"><div className="arch-layer"><strong>Buyer signature</strong><p>Establishes commercial intent for an immutable order version.</p><span className="arch-badge">Attributed intent</span></div><div className="arch-layer"><strong>ZK proof</strong><p>Establishes confidential mathematical consistency.</p><span className="arch-badge">Private validity</span></div><div className="arch-layer canonical"><strong>CapacityVault</strong><p>Establishes which commitment is current and spendable.</p><span className="arch-badge">Canonical authority</span></div></div><div><span className="premium-kicker">04 · Separation of authority</span><h2>No single layer is allowed to impersonate another.</h2><p>A database row cannot replace chain state. A valid proof cannot replace current-state checks. An auditor claim cannot replace consensus ordering. ThreadProof stays trustworthy by keeping those authorities narrow.</p></div></section></Reveal>
    </div><MarketingFooter /></main>;
}
